### ISSUE TITLE
Documentation generation failure

### ISSUE THREAD

**Issue by theDevSoham** [fairfield-programming/donovan#16]
Hi @William-McGonagle , I've forked and synced the repository and even after that, I'm running into an error while using donovan. The error message is something like: Error: ENOENT: no such file or directory, open 'C:\Users\Username\donovan\public\3fF7F52AaVf3.css'. 

Steps to generate error: 

1. Clone the repo and run `npm install`. 

2. After success, run `npm link` .

3. Then just run `donovan`

OS Used: Windows 10.

I'm attaching a screenshot of the error for a better understanding. 

![index js - donovan - Visual Studio Code 10-02-2023 00_51_29](https://user-images.githubusercontent.com/79685489/217918390-5106b3a0-c254-4b13-8cd9-8797bb1d31ef.png)

**Comment by William-McGonagle** [comment]
@theDevSoham 

Just found the problem– in the [`src/runPage.js`](https://github.com/fairfield-programming/donovan/blob/master/src/generator/runPage.js) file, we have a function called importCssFile but it's just a placeholder. If you remove the file, that should fix the error. 

Let me know if that works.

**Comment by theDevSoham** [comment]
Thanks a lot @William-McGonagle . That works like a charm.
