### ISSUE TITLE
Add Support for Tailwind and PostCSS

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/donovan#8]
I'm not really sure how tools like Webpack work, but pretty much we need to start mimicking their behaviors so that we can work with tools like Tailwind and PostCSS. This would allow our websites to look beautiful while still being modern and fast. 

If you're interested in taking a shot at this, please let me know.

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by William-McGonagle** [comment]
Hey @Rishav1707 –

If you would like to take this issue, I would be more than happy to assign it. That being said, it may be a bit easier to implement the Readme parsing– that might also get you more comfortable with the project too. 

Let me know what you think!

Cheers,
William McGonagle

**Comment by theDevSoham** [comment]
Hi @William-McGonagle  I've done some potential auto generation for tailwind in donovan. The issue is, while tailwind auto install behavior was implemented, at that time there was an error after running the document generation template. So I commented the public folder creation code and pushed it to another branch named "tailwind-generation". Currently it only generates tailwind file only and no site is generated. Would you like me to send over a pull request so that you can check the code? However no postCSS implementation is there

**Comment by William-McGonagle** [comment]
Hey @theDevSoham – 

When I started the project, I thought that it would make sense to generate the Tailwind files and PostCSS, but what I realized is that for Tailwind and PostCSS to work, you need Webpack (or some other packer). The problem with Webpack is that it completely conflicts with the Donovan build process. So, rather than trying to use Webpack, I think that a better approach that we can take is to emulate Webpack's core functionality. I know this sounds difficult but would actually be quite easy as packers are generally lightweight.  

Let me know what you think about this approach, or if you have any other ideas.

Cheers!
William McGonagle

**Comment by theDevSoham** [comment]
@William-McGonagle that sounds great. Though the approach I followed may vary. I opened the official tailwind site and followed the steps in code. The good thing about this is it generates the basic tailwind `output.css` in public directory. Now if the template you are using to generate the html have a link tag like this: `link rel="stylesheet" href="output.css"` I think the tailwind classes should just work. This is my idea, let me know what you think about it. Meanwhile, I would give generating the core functionality of webpack a try.

**Comment by William-McGonagle** [comment]
That sounds awesome– I think once we get the Tailwind working, the whole project will look great. Thanks @theDevSoham!

**Comment by William-McGonagle** [comment]
Hey @theDevSoham – I forgot to ask, but would you be interested in joining the FPA? We have around eleven full-time members, and you could run the Donovan project as we start to grow its size. 

Here's the invite to our [community discord](https://discord.gg/9GzPSkJNsS) if you're interested, though we use slack for our team.

**Comment by theDevSoham** [comment]
Hi @William-McGonagle . That's a really good opportunity. Would really love to discuss about this FPA offer. But before let me mention that I won't be able to relocate anytime soon as I'm a student right now based in India currently pursuing my final year. That's a reason I will need to be a remote joinee. Is that possible?

**Comment by William-McGonagle** [comment]
Hey @theDevSoham – Don't worry, we're just an open-source, non-profit so it is very low-stress and we are fully remote. We have a few engineers at University right now, and I should note that we are fully volunteer-run (so there are no paid positions at the FPA).

If you're interested, you can join the Discord server and send me a message (williammcgonagle#4644).

**Comment by theDevSoham** [comment]
@William-McGonagle Thanks. Texting you right away in discord
