### ISSUE TITLE
Add a Basic CLI

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/donovan#9]
We need a CLI for the project that supports arguments and commands but still allows us to just run `npx donovan` to run the documentation generator. 

Some nice CLI commands would be 'help', 'about' (tells version info), 'init' (generates the config file), and 'clean' (removes public and template folders).

If you're interested in implementing this, it should take no extra dependencies– let me know in the comments if you're up for the challenge!

**Comment by theDevSoham** [comment]
Hi @William-McGonagle , I forked the repository and tried this challenge. It's pretty much working out according to me. Apart from the 'init' functionality all the other commands seem to work well on my end. I've pushed all the changes to another branch called "cli-commands" in my forked repo. Shall I send a PR so that you can check out the code?

**Comment by William-McGonagle** [comment]
Yes– send in a PR and I can check it out. Thanks, @Mark-42-max

**Comment by theDevSoham** [comment]
My pleasure😊. I've attached a PR. Please check @William-McGonagle

**Comment by theDevSoham** [comment]
One more thing I wanna mention is I might need your help in implementing the 'init' functionality. Need some discussion about generating config file

**Comment by William-McGonagle** [comment]
Yes @Mark-42-max, I saw your pull request. It looked great. The init function should create a file in `.github/donovan.json`, with content from the 'default config' function. The 'default config' function already prefills data using the name of folders and readme data.

**Comment by theDevSoham** [comment]
Thanks a lot @William-McGonagle . I've sent a PR regarding this 'init' behaviour. The files are created accordingly although I'm not sure I've populated the right config content into the ```donovan.json``` file. Could you please check and let me know?

**Comment by William-McGonagle** [comment]
The pull request looked great– I just merged it in @theDevSoham. Thanks for the contributions!
